---
title: "sim-process"
author: "Hussein Al-Asadi"
date: "November 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('rstan')
library('MASS')
library('boot')
```

Simulate under a very simple model

```{r}
N = 10
eta_sq <- 1
rho_sq <- 1
sigma_sq <- 1
mu = rep(0, N)
x = runif(N)
P=1000
Sigma = matrix(nrow = N, ncol = N, 0)
for (i in 1:(N-1)){
  for (j in (i+1):N){
    Sigma[i,j] <- exp(-(x[i]-x[j])^2)
    Sigma[j,i] <- Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] <- 1 + 1
}
library(MASS)

# P x N matrix
y = mvrnorm(n=P, mu=mu, Sigma=Sigma)

test_data = list(N=N, P = P, x = x, y = y)

fit1 = stan(file = "gp-fit.stan", data =test_data, iter=1000, chains=1)
```


### simulate under the model  
```{r}
alpha = 1000
beta = 1000
phi = 1
# 100 individuals and 100 SNPs
N = 10
P = 100


euc.dist <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))


Sigma <- matrix(nrow=N, ncol = N, 0)
mu_vec <- runif(P)
t <- runif(N)*10000
l <- t(matrix(nrow=N, ncol = 2, runif(N*2))*1000)
for (i in 1:(N-1)){
  for (j in (i+1):N){ 
    Sigma[i,j] = phi * exp(-euc.dist(t[i],t[j])/beta); # exp(-euc.dist(l[,i], l[,j])/alpha);
    Sigma[j,i] = Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] = phi + 0.1
}

y <- matrix(nrow = P, ncol = N, 0)
for (i in 1:P){
  mu = rep(1, N)*mu_vec[i]
  y[i,] = mvrnorm(n=1, mu=mu, Sigma=Sigma)
}

f = inv.logit(y)

X = matrix(nrow = P, ncol = N, 0)
for (i in 1:N){
  for (j in 1:P){
    X[j,i] = rbinom(n=1, size=1, prob=f[j,i])
  }
}

gp_data <- list(N=N, P=P, t=t, l = l, y=X)

fit1 <- stan(file = "simple.stan", data = gp_data, iter = 1000, chains = 1)

```