---
title: "stein-project"
author: "Hussein Al-Asadi"
date: "November 18, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('rstan')
library('MASS')
library('boot')
```

## Simulation under a simple model

```{r, cache=TRUE}
N = 30
rho_sq <- 0.5
phi <- 0.1
mu = rep(0, N)
x = 10 * runif(N)
P=10
Sigma = matrix(nrow = N, ncol = N, 0)
for (i in 1:(N-1)){
  for (j in (i+1):N){
    Sigma[i,j] <- phi * exp(-rho_sq * (sqrt((x[i]-x[j])^2)))
    Sigma[j,i] <- Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] <- phi + 0.01
}

theta = mvrnorm(n=P, mu=mu, Sigma=Sigma)
y = matrix(nrow=P, ncol = N, 0)
for (i in 1:N){
  for (j in 1:P){
    y[j,i] = rbinom(n=1,size=1, prob = inv.logit(theta[j,i]))
  }
}

test_data = list(N=N, P=P, x = x, y = y)

fit = stan(file = "simple-spatial.stan", data =test_data, iter=10000, chains=1)
stan_plot(fit, pars = c("phi", "rho_sq"))
plot(theta, colMeans(extract(fit)$theta), xlab = "true theta", ylab = "estimated theta")
abline(0,1, col="red", lwd=2)
```

## fixing rho greatly helps in the estimation

```{r}
N = 30
phi <- 1
mu = rep(0, N)
x = 10 * runif(N)
P=10
Sigma = matrix(nrow = N, ncol = N, 0)
for (i in 1:(N-1)){
  for (j in (i+1):N){
    Sigma[i,j] <- phi * exp(-(sqrt((x[i]-x[j])^2)))
    Sigma[j,i] <- Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] <- phi + 0.01
}

theta = mvrnorm(n=P, mu=mu, Sigma=Sigma)
y = matrix(nrow=P, ncol = N, 0)
for (i in 1:N){
  for (j in 1:P){
    y[j,i] = rbinom(n=1,size=1, prob = inv.logit(theta[j,i]))
  }
}

test_data = list(N=N, P=P, x = x, y = y)

fit = stan(file = "simple-spatial-fixed.stan", data =test_data, iter=10000, chains=1)
stan_plot(fit, pars = c("eta_sq", "rho_sq"))
plot(theta, colMeans(extract(fit)$theta), xlab = "true theta", ylab = "estimated theta")
abline(0,1, col="red", lwd=2)
phi_hat <- mean(extract(fit)$phi, na.rm=T)

```



## grouping the data helps

```{r, cache=TRUE}
N = 10
rho_sq <- 0.5
phi <- 0.1
mu = rep(0, N)
x = 10 * runif(N)
P=10
Sigma = matrix(nrow = N, ncol = N, 0)
for (i in 1:(N-1)){
  for (j in (i+1):N){
    Sigma[i,j] <- phi * exp(-rho_sq * (sqrt((x[i]-x[j])^2)))
    Sigma[j,i] <- Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] <- phi + 0.01
}

theta = mvrnorm(n=P, mu=mu, Sigma=Sigma)
y = matrix(nrow=P, ncol = N, 0)
for (i in 1:N){
  for (j in 1:P){
    y[j,i] = rbinom(n=1,size=10, prob = inv.logit(theta[j,i]))
  }
}

test_data = list(N=N, P=P, x = x, y = y)

fit = stan(file = "simple-spatial-grouped.stan", data =test_data, iter=10000, chains=1)
stan_plot(fit, pars = c("phi", "rho_sq"))
plot(theta, colMeans(extract(fit)$theta), xlab = "true theta", ylab = "estimated theta")
abline(0,1, col="red", lwd=2)
rho_sq_hat <- mean(extract(fit)$rho_sq, na.rm=T)
phi_hat <- mean(extract(fit)$phi, na.rm=T)
```

## simple space-time model (grouped)

```{r}
euc.dist <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))


N = 10
n <- sample(1:10, 10)

alpha = 1
beta = 1
phi = 1
mu = rep(0, N)
x = 10 * runif(N)
t = matrix(10 * runif(2*N), nrow=N, ncol = 2)
P=100
Sigma = matrix(nrow = N, ncol = N, 0)
for (i in 1:(N-1)){
  for (j in (i+1):N){
    Sigma[i,j] <- phi * exp(-euc.dist(x[i], x[j])/alpha) * exp(-euc.dist(t[i,], t[j,])/beta);
    Sigma[j,i] <- Sigma[i,j]
  }
}

for (k in 1:N){
  Sigma[k,k] <- phi + 0.01
}

theta = mvrnorm(n=P, mu=mu, Sigma=Sigma)
y = matrix(nrow=P, ncol = N, 0)
for (i in 1:N){
  for (j in 1:P){
    y[j,i] = rbinom(n=1,size=n[i], prob = inv.logit(theta[j,i]))
  }
}

test_data = list(N=N, P=P, n = n, x = x, t=t,y = y)

fit = stan(file = "simple-spatial-time-grouped.stan", data =test_data, iter=10000, chains=1)
stan_plot(fit, pars = c("phi", "alpha", "beta"))
plot(theta, colMeans(extract(fit)$theta), xlab = "true theta", ylab = "estimated theta")
abline(0,1, col="red", lwd=2)
get_posterior_mean(fit, pars = c("beta", "alpha", "phi"))
fit = vb(stan_model(file = "simple-spatial-time-grouped.stan"), data = test_data)

```

## real data analysis


First, we fit the variance and spatial smoothness parameter with the modern data only.

```{r}



```